// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'generalContainer': string;
  'off': string;
  'restContainer': string;
  'restItem': string;
  'section5': string;
}
export const cssExports: CssExports;
export default cssExports;
