// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'field': string;
  'form': string;
  'section6': string;
  'submit': string;
}
export const cssExports: CssExports;
export default cssExports;
