// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'barEmptySpace': string;
  'barFirstColumnSeats': string;
  'barItself': string;
  'barPrice': string;
  'barSecondColumn': string;
  'barSecondColumnSeats': string;
  'barZone': string;
  'barZoneWrapper': string;
  'centerPrice': string;
  'centerZone': string;
  'centerZoneWrapper': string;
  'corridor': string;
  'firstRow': string;
  'occupied': string;
  'picked': string;
  'restaurantContainer': string;
  'scene': string;
  'sceneZone': string;
  'seat': string;
  'secondRow': string;
  'table': string;
  'tableContainer': string;
  'tableFirstRow': string;
  'tableSecondRow': string;
  'tableThirdRow': string;
  'vipFirstRow': string;
  'vipPrice': string;
  'vipSecondRow': string;
  'vipThirdRow': string;
  'vipZone': string;
  'vipZoneWrapper': string;
  'wc': string;
}
export const cssExports: CssExports;
export default cssExports;
