// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'colorItem': string;
  'cross': string;
  'customContainer': string;
  'descriptionBody': string;
  'descriptionBtn': string;
  'deviceContainer': string;
  'deviceItem': string;
  'generalContainer': string;
  'off': string;
  'section3': string;
  'sizeItem': string;
  'typeContainer': string;
  'typeItem': string;
  'wantMore': string;
}
export const cssExports: CssExports;
export default cssExports;
