// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'cross': string;
  'descriptionBody': string;
  'descriptionBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
